/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.junit.selenium;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;

import java.util.List;

import static io.restassured.RestAssured.when;
import static org.junit.jupiter.api.Assertions.assertEquals;

@Testcontainers
class JuiceTest {

    @Container
    public static GenericContainer juiceShopContainer = new GenericContainer(DockerImageName.parse("bkimminich/juice-shop:v13.0.3"))
            .withExposedPorts(3000);

    private static String address;
    private static Integer port;

    static WebDriver driver;

    @BeforeAll
    static void setup() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();

        address = juiceShopContainer.getHost();
        port = juiceShopContainer.getFirstMappedPort();
    }

    @AfterAll
    static void teardown() {
        driver.quit();
    }

    @Test
    void exampleSeleniumTest() throws InterruptedException {
        driver.get(String.format("http://%s:%s", address, port));
        assertEquals(String.format("http://%s:%s/#/", address, port), driver.getCurrentUrl());

        driver.findElement(By.className("close-dialog")).click();

        Thread.sleep(1000);

        List<WebElement> apple_juice = driver.findElements(By.className("product"));
        apple_juice.get(0).click();

        Thread.sleep(2000);

        driver.findElement(By.className("close-dialog")).click();
    }

    @Test
    void exampleApiTest() {
        when()
                .get(String.format("http://%s:%s/rest/products/search?q=", address, port))
        .then()
                .statusCode(200);
    }
}
